/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2015
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/

package com.ericsson.itpf.security.pki.cmdhandler.api.types;

/**
 * Enumeration of the supported com.ericsson.itpf.security.pki.command types.
 * 
 * <p>
 * An entry should be added here for each new supported PKI com.ericsson.itpf.security.pki.cmdhandler.command.handler
 * </p>
 * Created by xsumnan on 29/03/2015.
 */
public enum PkiCommandType {


    CONFIGMGMTENABLE, CONFIGMGMTDISABLE, ENTITYMANAGEMENTEXPORT, ENTITYMANAGEMENTIMPORT, PROFILEMANAGEMENTCREATE, PROFILEMANAGEMENTLIST, PROFILEMANAGEMENTUPDATE, PROFILEMANAGEMENTDELETE, CONFIGMGMTLIST, CONFIGMGMTUPDATE, PROFILEMANAGEMENTIMPORT, PROFILEMANAGEMENTEXPORT, CACERTIFICATEMANAGEMENTGENERATE, CACERTIFICATEMANAGEMENTREISSUE, CACERTIFICATEMANAGEMENTLIST, CACERTIFICATEMANAGEMENTEXPORT, CACERTIFICATEMANAGEMENTLISTHIERARCHY, CERTIFICATEMANAGEMENTLIST, CERTIFICATEMANAGEMENTGENERATECSR, ENTITYCERTMANAGEMENTGENARATE, ENTITYCERTMANAGEMENTGENARATEWITHOUTCSR, ENTITYCERTMANAGEMENTREISSUE, ENTITYCERTMANAGEMENTLIST, ENTITYCERTMANAGEMENTEXPORT, ENTITYMANAGEMENTCREATE, ENTITYMANAGEMENTLIST, ENTITYMANAGEMENTUPDATE, ENTITYMANAGEMENTDELETE, CONFIGMANAGEMENTCATEGORYCREATE, CONFIGMANAGEMENTCATEGORYUPDATE, CONFIGMANAGEMENTCATEGORYLIST, CONFIGMANAGEMENTCATEGORYDELETE, EXTERNALCACERTIMPORT, EXTERNALCAUPDATECRL, EXTERNALCALIST, EXTERNALCAREMOVE, EXTERNALCACERTEXPORT, EXTERNALCACONFIGCRL, REVOCATIONMANAGEMENTREVOKECACERT, REVOCATIONMANAGEMENTREVOKEENTITYCERT, PROFILEMANAGEMENTVIEW, CRLMANAGEMENTLIST, CRLMANAGEMENTGENERATE, CRLMANAGEMENTDOWNLOAD, TRUSTMANAGEMENTPUBLISH, TRUSTMANAGEMENTUNPUBLISH, CRLMANAGEMENTPUBLISH, CRLMANAGEMENTUNPUBLISH, TRUSTMANAGEMENTLIST, TRUSTMANAGEMENTLISTBYSTATUS
    ,CERTIFICATEMANAGEMENTIMPORT, EXTERNALCAREMOVECRL, SECGWCERTMANAGEMENT


}
