ALTER TABLE IF EXISTS Entity_CSR
DROP CONSTRAINT IF EXISTS fk_Entity_CSR_CSR_Id;

ALTER TABLE IF EXISTS Entity_CSR
DROP CONSTRAINT IF EXISTS fk_Entity_Data_Entity_Id;

DROP TABLE IF EXISTS Entity_CSR;

ALTER TABLE IF EXISTS CA_CSR
DROP CONSTRAINT IF EXISTS fk_Certificate_Request_CSR_Id;

ALTER TABLE IF EXISTS CA_CSR
DROP CONSTRAINT IF EXISTS fk_CA_Data_CA_Id;

DROP TABLE IF EXISTS CA_CSR;

ALTER TABLE IF EXISTS Certificate_Generation_Info
DROP CONSTRAINT IF EXISTS fk_Signature_Algorithm_Id;

ALTER TABLE IF EXISTS Certificate_Generation_Info
DROP CONSTRAINT IF EXISTS fk_Certificate_Request_CSR;

ALTER TABLE IF EXISTS Certificate_Generation_Info
DROP CONSTRAINT IF EXISTS fk_CA_Data_CA_Entity_Info;

ALTER TABLE IF EXISTS Certificate_Generation_Info
DROP CONSTRAINT IF EXISTS fk_Entity_Data_Entity_Info;

ALTER TABLE IF EXISTS Certificate_Generation_Info
DROP CONSTRAINT IF EXISTS fk_CA_Data_Issuer_CA;

ALTER TABLE IF EXISTS Certificate_Generation_Info
DROP CONSTRAINT IF EXISTS fk_Key_Generation_Algorithm_Id;

DROP TABLE IF EXISTS Certificate_Generation_Info;

DROP TABLE IF EXISTS Algorithm;

ALTER TABLE IF EXISTS CA_Certificate
DROP CONSTRAINT IF EXISTS fk_CA_Certificate_CA_Id;

ALTER TABLE IF EXISTS CA_Certificate
DROP CONSTRAINT IF EXISTS fk_CA_Certificate_Certificate_Id;

DROP TABLE IF EXISTS CA_Certificate;

ALTER TABLE IF EXISTS Certificate_Data
DROP CONSTRAINT IF EXISTS fk_CA_Data_Id;

DROP TABLE IF EXISTS CA_Data;

ALTER TABLE IF EXISTS Entity_Certificate
DROP CONSTRAINT IF EXISTS fk_Entity_Certificate_Certificate_id;

ALTER TABLE IF EXISTS Entity_Certificate
DROP CONSTRAINT IF EXISTS fk_Entity_Certificate_Entity_Id;

DROP TABLE IF EXISTS Entity_Certificate;

DROP TABLE IF EXISTS Entity_Data;

ALTER TABLE IF EXISTS Certificate_Request
DROP CONSTRAINT IF EXISTS fk_Certificate_Request_Status_Id;

ALTER TABLE IF EXISTS Certificate_Data
DROP CONSTRAINT IF EXISTS fk_Certificate_Data_CSR_ID;

ALTER TABLE IF EXISTS Certificate_Data
DROP CONSTRAINT IF EXISTS fk_Certificate_Data_Status_Id;

DROP TABLE IF EXISTS Certificate_Request;
DROP TABLE IF EXISTS Certificate_Data;

DROP TABLE IF EXISTS Certificate_Status;
DROP TABLE IF EXISTS Certificate_Request_Status;

DROP SEQUENCE IF EXISTS SEQ_CSR_ID;
DROP SEQUENCE IF EXISTS SEQ_CERTIFICATE_ID;
DROP SEQUENCE IF EXISTS SEQ_CA_ID;
DROP SEQUENCE IF EXISTS SEQ_ENTITY_ID;
DROP SEQUENCE IF EXISTS SEQ_ALGORITHM_ID;
DROP SEQUENCE IF EXISTS SEQ_CERTIFICATE_GENERATION_INFO_ID;