/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 06:55:41 PM IST 
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import java.io.Serializable;

public class CredentialManagerAuthorityKeyIdentifier extends CredentialManagerCertificateExtension implements Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 5865145675846427402L;
    protected boolean byKeyIdentifier;
    protected boolean byAuthorityCertIssuerAndSerialNumber;

    /**
     * Gets the value of the byKeyIdentifier property.
     * 
     */
    public boolean isByKeyIdentifier() {
        return byKeyIdentifier;
    }

    /**
     * Sets the value of the byKeyIdentifier property.
     * 
     */
    public void setByKeyIdentifier(final boolean value) {
        this.byKeyIdentifier = value;
    }

    /**
     * Gets the value of the byAuthorityCertIssuerAndSerialNumber property.
     * 
     */
    public boolean isByAuthorityCertIssuerAndSerialNumber() {
        return byAuthorityCertIssuerAndSerialNumber;
    }

    /**
     * Sets the value of the byAuthorityCertIssuerAndSerialNumber property.
     * 
     */
    public void setByAuthorityCertIssuerAndSerialNumber(final boolean value) {
        this.byAuthorityCertIssuerAndSerialNumber = value;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return " AuthorityKeyIdentifier: [ isCritical: " + critical + " byKeyIdentifier: " + byKeyIdentifier
                + " byAuthorityCertIssuerAndSerialNumber: " + byAuthorityCertIssuerAndSerialNumber + " ] ";
    }
}
