/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.13 at 06:55:41 PM IST
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;

public class CredentialManagerKeyUsage extends CredentialManagerCertificateExtension implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7351541484671737036L;

    @XmlElement(required = true)
    protected List<CredentialManagerKeyUsageType> keyUsageType;

    public CredentialManagerKeyUsage() {
        critical = true;
    }

    /**
     * Gets the value of the keyUsageType property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the keyUsageType property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getKeyUsageType().add(newItem);
     * </pre>
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CredentialManagerKeyUsageType }
     */
    public List<CredentialManagerKeyUsageType> getKeyUsageType() {
        if (keyUsageType == null) {
            keyUsageType = new ArrayList<CredentialManagerKeyUsageType>();
        }
        return keyUsageType;
    }

    /**
     * Sets the value of the keyUsageType property.
     *
     * @param keyUsageType
     *            the keyUsageType to set
     */
    public void setKeyUsageType(final List<CredentialManagerKeyUsageType> keyUsageType) {
        this.keyUsageType = keyUsageType;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return " Key Usage: [ iscritical: " + critical + " keyUsageType: " + keyUsageType + " ] ";
    }
}
