/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 06:55:41 PM IST 
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;

public class CredentialManagerAuthorityInformationAccess extends CredentialManagerCertificateExtension implements Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = -2250912776944362600L;

    @XmlElement(nillable = false, required = true)
    protected List<CredentialManagerAccessDescription> accessDescription = new ArrayList<CredentialManagerAccessDescription>();

    /**
     * @return the accessDescription
     */
    public List<CredentialManagerAccessDescription> getAccessDescription() {
        return accessDescription;
    }

    /**
     * @param accessDescription
     *            the accessDescription to set
     */
    public void setAccessDescription(final List<CredentialManagerAccessDescription> accessDescription) {
        this.accessDescription = accessDescription;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return " AuthorityInformationAccess: [ isCritical: " + critical + " AccessDescriptions: " + accessDescription + " ] ";
    }

}
