/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.13 at 06:55:55 PM IST
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ediPartyName complex type.
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ediPartyName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameAssigner" type="{}nonEmptyString" minOccurs="0"/>
 *         &lt;element name="partyName" type="{}nonEmptyString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ediPartyName", propOrder = {
    "nameAssigner",
    "partyName"
})
public class CredentialManagerEdiPartyName implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 869117501615076120L;
    protected String nameAssigner;
    protected String partyName;

    /**
     * Gets the value of the nameAssigner property.
     *
     * @return
     *         possible object is
     *         {@link String }
     */
    public String getNameAssigner() {
        return nameAssigner;
    }

    /**
     * Sets the value of the nameAssigner property.
     *
     * @param value
     *            allowed object is
     *            {@link String }
     */
    public void setNameAssigner(final String value) {
        nameAssigner = value;
    }

    /**
     * Gets the value of the partyName property.
     *
     * @return
     *         possible object is
     *         {@link String }
     */
    public String getPartyName() {
        return partyName;
    }

    /**
     * Sets the value of the partyName property.
     *
     * @param value
     *            allowed object is
     *            {@link String }
     */
    public void setPartyName(final String value) {
        partyName = value;
    }

    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return " EDIPartyName: [ nameAssigner: " + nameAssigner + " partyName: " + partyName + " ] ";
    }
}
