/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.13 at 06:55:41 PM IST
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;

import org.bouncycastle.asn1.x509.KeyPurposeId;

public class CredentialManagerExtendedKeyUsage extends CredentialManagerCertificateExtension implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -5599467949832520029L;

    @XmlElement(required = true, nillable = true)
    protected List<CredentialManagerKeyPurposeId> keyPurposeId;

    /**
     * Gets the value of the keyPurposeId property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the keyPurposeId property.
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getKeyPurposeId().add(newItem);
     * </pre>
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link KeyPurposeId }
     */
    public List<CredentialManagerKeyPurposeId> getKeyPurposeId() {
        if (keyPurposeId == null) {
            keyPurposeId = new ArrayList<CredentialManagerKeyPurposeId>();
        }
        return keyPurposeId;
    }

    /**
     * Sets the value of the keyPurposeId property.
     *
     * @param keyPurposeId
     *            the keyPurposeId to set
     */
    public void setKeyPurposeId(final List<CredentialManagerKeyPurposeId> keyPurposeId) {
        this.keyPurposeId = keyPurposeId;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return " ExtendedKeyUsage: [ isCritical: " + critical + " keyPurposeId: " + keyPurposeId + " ] ";
    }

}
