/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.13 at 06:55:41 PM IST
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for accessMethods.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="accessMethods">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="caIssuers"/>
 *     &lt;enumeration value="ocsp"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "accessMethods")
@XmlEnum
public enum CredentialManagerAccessMethod {
    @XmlEnumValue("caIssuers") CA_ISSUER("1.3.6.1.5.5.7.48.2"), @XmlEnumValue("ocsp") OCSP("1.3.6.1.5.5.7.48.1");

    String value;

    CredentialManagerAccessMethod(final String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static CredentialManagerAccessMethod fromValue(final String v) {
        return valueOf(v);
    }

}
