/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.13 at 06:55:41 PM IST
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;

public class CredentialManagerBasicConstraints extends CredentialManagerCertificateExtension implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -9162100827695821256L;
    @XmlElement(required = true)
    protected boolean enabled;
    @XmlElement(name = "cA", required = false)
    protected boolean cA;
    @XmlElement(required = false)
    @XmlSchemaType(name = "positiveInteger")
    protected int pathLenConstraint;

    /**
     * @return the enabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * @param enabled
     *            the enabled to set
     */
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Gets the value of the ca property.
     */
    public boolean isCA() {
        return cA;
    }

    /**
     * Sets the value of the ca property.
     */
    public void setCA(final boolean value) {
        cA = value;
    }

    /**
     * Gets the value of the pathLenConstraint property.
     *
     * @return possible object is int
     */
    public int getPathLenConstraint() {
        return pathLenConstraint;
    }

    /**
     * Sets the value of the pathLenConstraint property.
     *
     * @param value
     *            allowed object is int
     */
    public void setPathLenConstraint(final int value) {
        pathLenConstraint = value;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return " Basic COnstraints: [ isCritical: " + critical + " enabled: " + enabled + " ca: " + cA + " pathLenConstraint: " + pathLenConstraint
                + " ] ";
    }
}
