/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2020
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.13 at 06:55:41 PM IST
//

package com.ericsson.oss.itpf.security.credmservice.api.model;

import javax.xml.bind.annotation.XmlEnumValue;

public enum CredentialManagerKeyPurposeId {

    @XmlEnumValue("id_kp_clientAuth") ID_KP_CLIENT_AUTH("id_kp_clientAuth"),
    @XmlEnumValue("id_kp_codeSigning") ID_KP_CODE_SIGNING("id_kp_codeSigning"),
    @XmlEnumValue("id_kp_emailProtection") ID_KP_EMAIL_PROTECTION("id_kp_emailProtection"),
    @XmlEnumValue("id_kp_timeStamping") ID_KP_TIMESTAMPING("id_kp_timeStamping"),
    @XmlEnumValue("id_kp_OCSPSigning") ID_KP_OCSP_SIGNING("id_kp_OCSPSigning"),
    @XmlEnumValue("id_kp_serverAuth") ID_KP_SERVER_AUTH("id_kp_serverAuth");
    private final String value;

    CredentialManagerKeyPurposeId(final String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredentialManagerKeyPurposeId fromValue(final String v) {
        for (final CredentialManagerKeyPurposeId c : CredentialManagerKeyPurposeId.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
