"cmedit" (* slogan = "Command set to read, manipulate, and export Configuration Management data" *) WS "create" (* slogan = "Creates a single MO instance" *) WS PREDEF_FDN [ CREATE_ATTRIBUTE_SETTER_LIST ] { CREATE_OPTIONS } (* unique = "true" *)

CREATE_ATTRIBUTE_SETTER_LIST ::= CREATE_ATTRIBUTE_SETTER_FIRST { ( ";" (* hide = "true"  slogan = "Semi-colon used to add another attribute to the list." *) | "," (* slogan = "Comma used to add another attribute to a list." *) ) CREATE_ATTRIBUTE_SETTER_REPS }
CREATE_ATTRIBUTE_SETTER_FIRST ::= WS <attribute_name> (* slogan = "Name of Attribute to create" *) "=" <attribute_value> (* regex = "^(?:\-\d|[\w\$\=]+)[\w\$\-]*$" inputType = "wrapDoubleQuotes,wrapSingleQuotes,wrapSquareBrackets,wrapParentheses,wrapCurlyBrackets" slogan = "MO Attribute Value to create.  String values - A wildcard can be used E.g. userLabel==Test* " *)
CREATE_ATTRIBUTE_SETTER_REPS ::= <attribute_name> (* slogan = "Name of Attribute to create" *) "=" <attribute_value> (* regex = "^(?:\-\d|[\w\$\=]+)[\w\$\-]*$" inputType = "wrapDoubleQuotes,wrapSingleQuotes,wrapSquareBrackets,wrapParentheses,wrapCurlyBrackets" slogan = "MO Attribute Value to create.  String values - A wildcard can be used E.g. userLabel==Test* " *)
CREATE_OPTIONS ::= ( CREATE_NAMESPACE CREATE_VERSION | OUTPUT_FORMAT )

CREATE_NAMESPACE ::= WS ( "-ns" (* hide = "true" *) | "-namespace" (* hide = "true" *) | "--namespace" (* slogan = "[Optional] Query Network Data by specific modeled namespace. Tip: -ns for short" *) ) CREATE_NAMESPACE_INPUT
CREATE_NAMESPACE_INPUT ::= ( WS | "=" (* hide = "true" *) ) <namespace> (* inputType = "wrapDoubleQuotes,wrapSingleQuotes" slogan = "Name of specific Modeled Namespace to create. E.g. MSRBS_V1_eNodeBFunction" *)
CREATE_VERSION ::= WS ( "-v" (* hide = "true" *) | "-version" (* hide = "true" *) | "--version" (* slogan = "[Optional] Query Network Data by modeled version. Tip: -v for short" *) ) CREATE_VERSION_INPUT
CREATE_VERSION_INPUT ::= ( WS | "=" (* hide = "true" *) ) <version> (* inputType = "version" slogan = "Name of specific modeled version to create.  E.g. H.1.140" *)
CONFIGURATION ::= WS ( "-c" (* hide = "true" *) | "--config" (* slogan = "[Optional] Execute command on an existing Configuration. Tip: shorthand is -c. Note: 'live' is default" *) ) "=" <configuration> (* slogan = "Name of Configuration to execute the command against. 'Live' is default" *)
OUTPUT_FORMAT ::= WS ( "-l" (* hide = "true" *) | "-list" (* hide = "true" *) | "--list" (* slogan = "[Optional] Display output results in list format. This is default output format.  Tip: -l for short" *) | "-t" (* hide = "true" *) | "-table" (* hide = "true" *) | "--table" (* slogan = "[Optional] Display output results in tabular format.  Tip: -t for short" *) )
